Nucleotids = ["A" ,"T", "G", "C"]

fasta1 = "CGCTCCGGTTCTAAAAATGAGTTATGTTTTGCCATGATATGCCCCCCAACGATTGTTGTCAGTAGTGAAGCCTAACTCGATCGAAGCGTCTACCCAGGGGTAAACGTCCTTTCATCGTTCTGGAGTTAATGGTGACCTAATCGAATGCGATGTGAGTATTCCGATAAACGTGCTGCAGGCCGGCGTTAACTTACGTCCCGAACTTGGCGTGGGCTACCCTATGTGCATTTGTGTCAGAGGGCACACAATATCGAGTTGTTGTGTGCATACCTGTGCCATCGGTCTAGACGGCCGTCGAGGTAACGACAATACTCAATGGCGCTAGTACGTGCCATAAGGAGCTTTCGAACATTGATCGTCCCACATATCACCGTCATGTCGCTTACTAGTAAAAGTCCTCCCATGGGTGCCTAAAGAGAAAAGAAAGATAGTCCCAAGTGCCGAGTGTCTGGTGCACCAAATGATCACGAATGTGCGCCGGATAGATGCACATCTAGAACGCCAGGCAAATAGCTTTTGACCCTGACCCTCGACTAATGGGTCTTGGCCCCAGTCTACGCGGAGTCCTTATATATCTGTCAGTCCGTCTAGAGTTAGTATGGCCTAACTATCAATCTCTGTACTGTATGTAAGAAGGTAGGCTTATTGCCCGGTTACGTCACTAGGAGTCCTACTGGTAGCCCACTTAGCCCATCGGGCATCAAGACGTTAAAACCCCCTCAAGCGAAAGCTGCACTGGTCCAAGGTCGCTCTGGGATAGGCTTAATGTACGCTGTCCGAATCGTAAGCACCGCTTACTGTCATAGAATCCCCTTTCTCGGCGCCCGTTAATCTGATTTATATAGGTTGCGGAGGGTAAAGCAGCAGTGGCCACCGTACTGTACTTCGATTGGCGTGACAGCCGAGAAACAGCACGTCCACGCAAAAACTAATTCGGGCTGCATTCACCAGTGAACTTTCGAAAT"

complementing = []

for a in fasta1:
    if a == "A":
        complementing.append("T")
    elif a == "T":
        complementing.append("A")
    elif a == "C":
        complementing.append("G")
    elif a == "G":
        complementing.append("C")
    else:
        print("Error")

complementary_strand = ''.join(complementing)

print(complementary_strand[::-1])
